clone:
  skip_verify: true
build:
  image: alpine:latest
  commands:
    - echo 'done'

publish:
  docker:
    username: blackicebird
    password: comeon
    email: blackicebird@126.com
    repo: blackicebird/hello-2048
    tag: 
      - latest
      - 2.0.$$BUILD_NUMBER
    load: docker/hello-2048.tar
    save:
      destination: docker/hello-2048.tar
      tag: latest
cache:
  mount:
    - docker/hello-2048.tar
